kind: Pod
apiVersion: v1
metadata:
  name: probe-tests
spec:
  containers:
  - name: probe-test-container
    image: centos:7
    command:
    - sh
    - -c
    - >
      echo "Waiting for 30 seconds to go live" &&
      for i in {1..30}; do echo "."; sleep 1; done &&
      touch /tmp/alive &&
      echo "Now waiting for 30 seconds to go die" &&
      for i in {1..30}; do echo "."; sleep 1; done &&
      rm /tmp/alive &&
      echo "Going to sleep mode" &&
      sleep inf
